# This is a basic workflow to help you get started with Actions

name: Build List

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install modules
        run: yarn
      - name: Update List and validate
        run: node actions/createChainsAndERC20List.js
      - name: Create Chain Lists for Subnet Explorer
        run: node actions/createSubnetExplorerChainsList.js
      - name: Create Contracts Dictionary for Subnet Explorer
        run: node actions/createSubnetExplorerContractsList.js
      - name: Create Address List
        run: node actions/createAddressList.js
      - name: commit new file
        uses: EndBug/add-and-commit@v7
        with:
          author_name: CI bot
          github_token: ${{ secrets.GITHUB_TOKEN }}
          push: true
