# This is a basic workflow to help you get started with Actions

name: Validate data

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: actions/core@v1
        with:
          node-version: "16"
      - name: Update List and validate
        run: node --experimental-json-modules actions/validate.js 
